# Generated by Django 3.2.5 on 2021-07-14 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='endDate',
            field=models.DateField(default=datetime.date(2021, 7, 14)),
        ),
    ]
