# Generated by Django 3.2.5 on 2021-07-14 08:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0002_alter_goal_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2021, 7, 14, 8, 15, 13, 23585, tzinfo=utc)),
        ),
    ]
