# Generated by Django 3.2.5 on 2021-07-13 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0002_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='endDate',
            field=models.DateField(default=datetime.date(2021, 7, 13)),
        ),
    ]
