# Generated by Django 3.2.5 on 2021-07-14 09:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0004_auto_20210714_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteration',
            name='goal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='needs.goal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goal',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2021, 7, 14, 9, 15, 26, 139634, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='iteration',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 14, 9, 15, 26, 141639, tzinfo=utc)),
        ),
    ]
