# Generated by Django 3.2.5 on 2021-07-14 09:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0005_auto_20210714_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2021, 7, 14, 9, 23, 4, 363823, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='iteration',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 14, 9, 23, 4, 367826, tzinfo=utc)),
        ),
    ]
