# Generated by Django 3.2.5 on 2021-07-14 15:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0006_auto_20210714_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='iteration',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 14, 15, 5, 6, 318782, tzinfo=utc)),
        ),
    ]
