# Generated by Django 3.2.5 on 2021-07-14 15:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0007_auto_20210714_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='endDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='iteration',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 14, 15, 7, 41, 660086, tzinfo=utc)),
        ),
    ]
