# Generated by Django 3.2.5 on 2021-07-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0009_alter_iteration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='iteration',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
