# Generated by Django 3.2.5 on 2021-08-27 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0011_alter_delivery_iteration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='needs.step'),
        ),
    ]
