# Generated by Django 3.2.5 on 2021-08-29 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('needs', '0012_alter_delivery_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteration',
            name='goal',
        ),
        migrations.AddField(
            model_name='iteration',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
