# Generated by Django 3.2.5 on 2021-09-27 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0013_auto_20210829_0529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=17)),
                ('need', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='needs.need')),
            ],
        ),
    ]
