# Generated by Django 3.2.5 on 2021-09-27 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0014_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icon',
            name='need',
        ),
    ]
