# Generated by Django 3.2.5 on 2021-11-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0020_alter_goal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
